[package]
name = "mc_chat_proc"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
mc_chat_core = { path = '../mc_chat_core' }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

